[package]
name = "histogram_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0.56"
image = "0.24.1"
indicatif = "0.17.0-rc.9"